[tool.black]
line-length = 150
target-version = ['py310']
force-exclude = '''
/(
  | migrations
)/
'''

[tool.isort]
profile = "black"
skip = "migrations"

[tool.ruff]
line-length = 150
target-version = "py310"
exclude = ["migrations"]

[tool.codespell]
skip = "./static/**"
ignore-words = ".codespellignore"
quiet-level = 2
